[workspace]
resolver = "2"
members = [
    "redis-command",
    "redis-command-gen",
    "redis-codec-core",
    "redis-proxy",
    "redis-proxy-common",
    "redis-proxy-server"]

[profile.release]
debug = true